# render.yaml
# This file tells Render exactly how to build and deploy the service.
# It uses an environment variable to force the correct Python version.

services:
  - type: web
    name: email-analyzer-backend
    # The runtime environment for the service
    runtime: python
    # The plan for the service (free tier)
    plan: free
    # The command to install all your libraries
    buildCommand: "pip install -r requirements.txt"
    # The command to start your web server
    startCommand: "gunicorn server:app"
    # Environment variables for the service
    envVars:
      # This is the new, more robust way to set the Python version
      - key: PYTHON_VERSION
        value: 3.11.9